;  PlatformIO Project Configuration File
; ESP32-C6 - Manito WebSocket Server con OTA
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c6-devkitc-1]
platform = espressif32
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800

;OTA: descomenta y ajusta cuando quieras subir por red
;upload_protocol = espota
;upload_port = 10.240.186.197   ; IP del ESP32-C6

lib_deps =
    links2004/WebSockets @ ^2.4.1
    bblanchon/ArduinoJson @ ^7.0.0
    tzapu/WiFiManager @ ^2.0.17

build_flags =
    -DCORE_DEBUG_LEVEL=0
